ec2 ssh key

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -98,39 +98,37 @@ jobs:
           docker build -t soniamohan/siansawebserver:latest .
           docker push soniamohan/siansawebserver:latest
 
-deploy:
-  needs: build_and_push
-  runs-on: ubuntu-latest
-  steps:
-
+  deploy:
+    needs: build_and_push
+    runs-on: ubuntu-latest
+    steps:
     # Add SSH Private Key
-    - name: Add SSH Key
-      run: |
+      - name: Add SSH Key
+        run: |
         echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
         chmod 600 ~/.ssh/ec2_key
-
     # Add EC2 to Known Hosts
-    - name: Add EC2 Host to Known Hosts
-      run: |
+      - name: Add EC2 Host to Known Hosts
+        run: |
         ssh-keyscan -H 18.201.46.129 >> ~/.ssh/known_hosts
 
-    # Deploy to EC2 Instance
-    - name: Deploy to EC2 instance
-      run: |
-        echo "Deploying to EC2 instance"
-        ssh -i ~/.ssh/ec2_key ubuntu@18.201.46.129 << 'EOF'
-          echo "Pulling the latest Docker image..."
-          docker pull soniamohan/siansawebserver:latest || { echo "Docker pull failed"; exit 1; }
 
-          echo "Stopping any existing container..."
-          docker stop siansawebserver-container || echo "No container to stop"
+      # Deploy to EC2 Instances
+      - name: Deploy to EC2 instance
+        run: |
+          echo "Deploying to EC2 instance"
+          ssh -i ~/.ssh/ec2_key ubuntu@18.201.46.129 << 'EOF'
+            echo "Pulling the latest Docker image..."
+            docker pull soniamohan/siansawebserver:latest || { echo "Docker pull failed"; exit 1; }
 
-          echo "Removing any existing container..."
-          docker rm siansawebserver-container || echo "No container to remove"
+            echo "Stopping any existing container..."
+            docker stop siansawebserver-container || echo "No container to stop"
 
-          echo "Starting the new container..."
-          docker run -d --name siansawebserver-container -p 8080:8080 soniamohan/siansawebserver:latest || { echo "Failed to start container"; exit 1; }
+            echo "Removing any existing container..."
+            docker rm siansawebserver-container || echo "No container to remove"
 
-          echo "Deployment complete!"
-        EOF
+            echo "Starting the new container..."
+            docker run -d --name siansawebserver-container -p 8080:8080 soniamohan/siansawebserver:latest || { echo "Failed to start container"; exit 1; }
 
+            echo "Deployment complete!"
+          EOF
